fix(task_either): tryCatch should take a Task<A>
nullpub/fun pull request #31
Opened 2022-01-26 23:45 UTC by pixeleet

This change is required, so the result of calling `tryCatch` with an `async` function correctly evaluate to `Task<Either<L,R>>` and not `Task<Either<L, Promise<R>>`

2022-01-27 00:13 UTC, baetheus commented
Hmmm, I believe this use case is covered by [fromFailableTask](https://github.com/nullpub/fun/blob/8b7072b4002a7eb68be547d93341bece289ef270/task_either.ts#L62). In other places ([Task](https://github.com/nullpub/fun/blob/main/task.ts#L36), [IO](https://github.com/nullpub/fun/blob/main/either.ts#L55), [IOEither](https://github.com/nullpub/fun/blob/main/io_either.ts#L31), [Either](https://github.com/nullpub/fun/blob/main/either.ts#L55), and [Option](https://github.com/nullpub/fun/blob/main/option.ts#L91)) I've tried to standardize on the input to tryCatch being a thunk. I'd like to keep this consistency. Is there a reason `fromFailableTask` isn't working for you?

2022-01-27 00:14 UTC, baetheus commented
It looks like the implementation for tryCatch in Option could be improved to handle the error case like the other tryCatch constructors do. Maybe that could be done here?

2022-01-27 00:23 UTC, pixeleet commented
Hmm, okay this works just the same as my tryCatch version, but I would contest that the second version is more idiomatic.
```
export const get_database_by_id = (database_id: string) =>
  pipe(
    () => databases.retrieve({ database_id }),
    TE.fromFailableTask(() => new Error(`Couldnt fetch db: ${database_id}`))
  );
```
the input is still "just a thunk" but one that is returning a promise, it should be so, because why not just use an Either if you can use sync functions in TaskEither tryCatch?
```
export const get_database_by_id = (database_id: string) =>
  tryCatch(
    () => databases.retrieve({ database_id }),
    () => new Error(`Couldnt fetch db: ${database_id}`)
  );
```

2022-01-27 00:32 UTC, pixeleet commented
> It looks like the implementation for tryCatch in Option could be improved to handle the error case like the other tryCatch constructors do. Maybe that could be done here?
How about?
```ts
export function tryCatch<A>(fa: () => A): Option<A> {
  return handleThrow<A, Option<A>>(fa, some, constNone)()
}
```

2022-01-27 11:05 UTC, pixeleet commented
> Hmmm, I believe this use case is covered by [fromFailableTask](https://github.com/nullpub/fun/blob/8b7072b4002a7eb68be547d93341bece289ef270/task_either.ts#L62). In other places ([Task](https://github.com/nullpub/fun/blob/main/task.ts#L36), [IO](https://github.com/nullpub/fun/blob/main/either.ts#L55), [IOEither](https://github.com/nullpub/fun/blob/main/io_either.ts#L31), [Either](https://github.com/nullpub/fun/blob/main/either.ts#L55), and [Option](https://github.com/nullpub/fun/blob/main/option.ts#L91)) I've tried to standardize on the input to tryCatch being a thunk. I'd like to keep this consistency. Is there a reason `fromFailableTask` isn't working for you?

I think the problem here is that tryCatch will come in to your mind much sooner than `fromFailableTask` and that it's not really a `TaskEither` if I can abuse it as an `IOEither` essentially. That is, not specifying that we expect the `F<A>` to be `() => Promise<A>` but letting it evaluate `IO<A>`, `Task<A>` all the same, is wrong imho.
```ts
tryCatch(() => someAsyncFn, String) // TaskEither<string, Promise<A>>
```
Now the Right is permanently wrapped in a promise and you can not really fold it away. 

This also breaks binding, because:
```ts
pipe(
  tryCatch(() => list_dbs(), String) // TaskEither<string, Promise<Db[]>>,
  TE.bindTo('dbs'),
  // () => Promise<Either<Error, { dbs: Promise<Db[]> }>>
)
```

Essentially the current signature permits using tryCatch as if it was synchronous while it is not, and should not be.
I believe the changes introduced fix that.

2022-01-30 19:06 UTC, baetheus commented
You might be right about tryCatch. Let me think about it a little more before committing to the breaking change.

2022-03-08 17:11 UTC, pixeleet commented
What's your take on this? Are we happy to move this forward? 
I've ended up on this implementation:
```ts
export function tryCatch<A, B>(
  fa: Task<A>,
  onError: (e: unknown) => B,
): TaskEither<B, A> {
  return handleThrow(
    fa,
    flow((a) => a.then(eitherRight).catch(flow(onError, eitherLeft))),
    flow(onError, (b) => eitherLeft<B, A>(b), resolve),
  );
}
```

2022-03-19 16:19 UTC, baetheus requested changes
Looks great, I like the catching of sync and async params after playing with it a bit.

2022-03-19 16:19 UTC, baetheus commented on task_either.ts
>  export function tryCatch<A, B>(
While you are here would you also mind adding documentation to this function?

2022-03-19 18:30 UTC, baetheus approved these changes
Awesome

2022-03-19 18:32 UTC, merged